name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Code pushed to branch
      with:
         ref: ${{ github.event.pull_request.head.ref }}
         fetch-depth: 0
    - uses: docker/build-push-action@v1
    - name: Build and push the Docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: chethanve/prototype
        tags: latest
        path: mqtt_subscriber
