name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file mqtt_subscriber/Dockerfile --tag my-image-name:$(date +%s)
