name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     # run: docker build . --file mqtt_subscriber/Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: mqtt_subscriber/Dockerfile
        repository: chethanve/prototype
        tag_with_ref: true
        tags: latest
